# Generated by Django 5.0.6 on 2024-07-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuID',
            field=models.IntegerField(),
        ),
    ]
